using Sim.Ui.Render;

namespace Sim.Ui.Trees.View;

/// <summary>
/// HEADLESS PREVIEW — paints a fixed set of scenarios of the Trees / Ages / Gallery screens
/// to SVG through the same TreesHost the game uses (sim-ui --trees-preview [dir]), so the
/// screens can be reviewed, and screenshotted by scripts/trees-preview.sh, without a GPU.
/// Every scenario is a sequence of UI actions and preview steps at fixed UI times, so the
/// files are byte-identical run to run.
/// </summary>
public static class TreesPreview
{
    public const double Width = 1280, Height = 800;

    public sealed record Scenario(string Name, string Description, Func<TreesHost, (TreesFrame Frame, double Now)> Build);

    public static IReadOnlyList<Scenario> Scenarios { get; } =
    [
        new("01-trees-overview", "The whole civilization: seven lens bands, one graph, legend panel.", h => Paint(h, 0.4)),
        new("02-trees-selected-prerequisites", "Engineering University selected; focus on its prerequisites; the details panel's why-view.",
            h => { Select(h, "institution.engineering-university"); Act(h, new SetFocusAction(FocusMode.Prerequisites)); return Paint(h, 0.8); }),
        new("03-trees-lineage-zoomed", "The demo cross-lens chain as a lineage, zoomed in on Engineering personnel.",
            h => { Select(h, "capability.engineering-personnel", center: true); Act(h, new SetFocusAction(FocusMode.Lineage)); Act(h, new ZoomAction(1.35)); return Paint(h, 1.1); }),
        new("04-trees-lens-industry-search", "The Industry lens with its cross-lens context, and a search for \"engin\".",
            h => { Act(h, new SetLensAction("INDUSTRY")); h.Ui.Search = "engin"; return Paint(h, 0.5); }),
        new("05-trees-filters", "State filter (researching, developing, operational) and Age filter (Age 02), hide mode.",
            h =>
            {
                Act(h, new ToggleStateFilterAction("researching"));
                Act(h, new ToggleStateFilterAction("developing"));
                Act(h, new ToggleStateFilterAction("operational"));
                Act(h, new SetAgeFilterAction("AGE_02"));
                Act(h, new SetFilterModeAction(FilterMode.Hide));
                return Paint(h, 0.5);
            }),
        new("06-trees-state-change", "Placeholder step 0 → 1, 0.35 s later: research completes (flash ring), a node is newly discovered, a stage pip fills.",
            h => { Paint(h, 0.0); h.Demo?.Next(); Select(h, "institution.engineering-university"); return Paint(h, 0.35); }),
        new("07-ages-current", "The Age view: Age 03 at 72 %, the milestone checklist, the Age's placeholder metadata.",
            h => { Act(h, new SetTabAction(TreesTab.Ages)); return Paint(h, 0.5); }),
        new("08-ages-transition-pending", "Placeholder step 2: an Age transition pending; a milestone selected.",
            h => { Paint(h, 0.0); h.Demo?.SetStep(1); Paint(h, 0.5); h.Demo?.SetStep(2); Act(h, new SetTabAction(TreesTab.Ages), 1.0); Act(h, new SelectMilestoneAction("M_03_03"), 1.0); return Paint(h, 1.4); }),
        new("09-ages-new-age", "Placeholder step 3: the new Age, 0.6 s after it was first reported (entry flash).",
            h => { Paint(h, 0.0); h.Demo?.SetStep(2); Paint(h, 0.5); h.Demo?.SetStep(3); Act(h, new SetTabAction(TreesTab.Ages), 0.5); return Paint(h, 1.1); }),
        new("10-gallery", "Building and unit placeholders drawn by the glyph grammar, with maturity, veterancy and animation samples.",
            h => { Act(h, new SetTabAction(TreesTab.Gallery)); return Paint(h, 0.9); }),
    ];

    /// <summary>Writes every scenario as &lt;name&gt;.svg into <paramref name="outDir"/>; returns the paths.</summary>
    public static IReadOnlyList<string> Run(string outDir, string contentDir, string? fontDir)
    {
        Directory.CreateDirectory(outDir);
        var written = new List<string>();
        foreach (Scenario s in Scenarios)
        {
            var host = new TreesHost(contentDir);
            (TreesFrame frame, _) = s.Build(host);
            string path = Path.Combine(outDir, s.Name + ".svg");
            File.WriteAllText(path, SvgWriter.Write(frame.Draw, Width, Height, fontDir));
            written.Add(path);
        }
        File.WriteAllText(Path.Combine(outDir, "README.md"),
            "# The Trees — preview frames\n\nGenerated by `sim-ui --trees-preview`. Each frame is painted by the same code the game runs.\n\n"
            + string.Join("\n", Scenarios.Select(s => $"- `{s.Name}` — {s.Description}")) + "\n");
        return written;
    }

    public static (TreesFrame Frame, double Now) Paint(TreesHost h, double now) =>
        (h.Frame(Width, Height, now, ApproxTextMeasure.Instance), now);

    /// <summary>Route one action as a click would: paint the frame at UI time
    /// <paramref name="now"/> (the host observes the sources then), then handle it.</summary>
    public static void Act(TreesHost h, TreesAction a, double now = 0.0)
    {
        TreesFrame f = h.Frame(Width, Height, now, ApproxTextMeasure.Instance);
        h.Handle(a, f);
    }

    public static void Select(TreesHost h, string nodeId, bool center = false)
    {
        if (h.Graph is not null && h.Graph.TryIndexOf(nodeId, out int i)) Act(h, new SelectNodeAction(i, center));
    }
}
