#!/usr/bin/env python3
"""Research content audit (ADR-029 addendum A — research corpus finalization).

Reads the AUTHORED research content (Sim.Data/content/research.json — no script generates
it any more) and writes docs/research-corpus-audit.md: the sets, the cost model and its
per-Age distribution, the curated Eurekas, the Group B pathway reachability, the
repeatables, the baseline capabilities, and the technique candidates carried forward from
the D-045 audit (docs/research-corpus-audit-d045.md). Every number is derived from the file;
nothing is tuned here.

Usage:  python3 scripts/research-content-audit.py            (write the audit)
        python3 scripts/research-content-audit.py --check    (exit 1 if the audit is stale)
"""
import math
import re
import sys
from collections import Counter

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
import research_lib as rl  # noqa: E402

AUDIT = rl.ROOT / "docs" / "research-corpus-audit.md"
HISTORICAL = rl.ROOT / "docs" / "research-corpus-audit-d045.md"
TOOL = "research-content-audit.py"

SCRIPTS = ["cuneiform", "hieroglyphic", "chinese_script"]
GROUP_B_GENERIC = ["law_code", "census", "geometry_practical", "astronomy_records", "abacus"]
GROUP_B_SPECIFIC = ["numeral_sexagesimal", "arithmetic_babylonian"]


def eureka_weights(node, ceiling):
    eus = node.get("eurekas") or []
    if not eus:
        return []
    if all(e.get("weight") is None for e in eus):
        return [ceiling / len(eus)] * len(eus)
    return [e["weight"] for e in eus]


def technique_candidates():
    rows = []
    if not HISTORICAL.exists():
        return rows
    text = HISTORICAL.read_text(encoding="utf-8")
    section = text.split("## Technique candidates", 1)[1].split("\n## ", 1)[0]
    for line in section.splitlines():
        m = re.match(r"\| `([a-z0-9_]+)` \| (A\d) \| (.+) \|$", line)
        if m:
            rows.append((m.group(1), m.group(2), m.group(3)))
    return rows


def build():
    content, sha = rl.load()
    g = rl.Graph(content)
    tuning = content["tuning"]
    ceiling = tuning["accelerationCreditCeilingFraction"]
    floor = tuning["effectiveCostFloorFraction"]
    U, K = tuning["costModel"]["U"], tuning["costModel"]["K"]
    nodes = g.nodes
    finite = g.finite()
    out = []
    w = out.append

    w("# Research corpus audit — the authored content")
    w("")
    w(f"Generated by `scripts/{TOOL}` from `Sim.Data/content/research.json` "
      f"(schema `{content['schema']}`, SHA-256 `{sha}`). Do not edit by hand; CI runs `--check`.")
    w("The content is AUTHORED (ADR-029 addendum A): it is the Director's finalization proposal, accepted by")
    w("the loader. The engine's loader is the validator; this file is an independent re-reading of the same")
    w("file. The D-045 audit of the earlier generated corpus is preserved as `docs/research-corpus-audit-d045.md`.")
    w("")

    # ---------------------------------------------------------------- sets
    w("## 1. Sets")
    w("")
    trees = Counter()
    for n in content["technologies"]:
        trees[f"Technology — {n.get('branch') or 'main'}"] += 1
    trees["Civics"] = len(content["civics"])
    w("| view | nodes |")
    w("|---|---|")
    for k in sorted(trees):
        w(f"| {k} | {trees[k]} |")
    w(f"| **all** | **{len(nodes)}** |")
    w("")
    w(f"- **finite** (every non-repeatable node — the only set counted for exhaustion and pacing): **{len(finite)}**")
    w(f"- **recursive** (the repeatables, excluded from finite exhaustion and pacing): **{len(g.recursive)}** — "
      + ", ".join(f"`{r}`" for r in content["researchSets"]["recursive"]))
    w(f"- **speculative_finite** (finite, counted): **{len(g.speculative)}** — "
      + ", ".join(f"`{s}`" for s in content["researchSets"]["speculative_finite"]))
    w(f"- registry entities: **{len(content['entities'])}**; entities with no knowledge requirement: "
      f"**{sum(1 for e in content['entities'] if not e.get('requires'))}** "
      + "(" + ", ".join(f"`{e['id']}`" for e in content["entities"] if not e.get("requires")) + ")")
    w(f"- completed research nodes at founding: **0** (no node is pre-completed; the baseline below lies outside the graph)")
    w("")

    # ---------------------------------------------------------------- costs
    w("## 2. Cost model — content-derived, no calibration adjustment")
    w("")
    w(f"`BaseCost = U × K^magnitude`, U = **{U}**, K = **{K}** (`tuning.costModel`); magnitude is the sum of six")
    w("per-node factors in `costRationale` (novelty, difficulty, material, institutional, breadth, prerequisite")
    w("complexity). Age enters only as a bounded prior inside difficulty and institutional; depth and node count")
    w("never enter.")
    w("")
    devs, adj, mags = [], 0, []
    for n in nodes:
        cr = n["costRationale"]
        model = U * K ** cr["magnitude"]
        devs.append((abs(n["cost"] - model), abs(n["cost"] - model) / n["cost"], n["id"]))
        if cr.get("calibration_adjustment", 0) != 0:
            adj += 1
        mags.append(cr["magnitude"])
    worst_abs = max(devs)
    worst_rel = max(devs, key=lambda d: d[1])
    w(f"- nodes with a non-zero calibration adjustment: **{adj}**")
    w(f"- largest |cost − U·K^m|: **{worst_abs[0]:.2f} RP** (`{worst_abs[2]}`); largest relative: "
      f"**{100 * worst_rel[1]:.2f} %** (`{worst_rel[2]}`) — authored costs are rounded to tens; the loader")
    w("  accepts max(5 RP, 0.1 % of cost)")
    # Variance of log-cost explained by Age (between-Age share of total variance).
    logs = {a: [math.log(n["cost"]) for n in finite if n["age"] == a] for a in rl.AGES}
    allv = [v for a in rl.AGES for v in logs[a]]
    mu = sum(allv) / len(allv)
    total_ss = sum((v - mu) ** 2 for v in allv)
    between = sum(len(logs[a]) * (sum(logs[a]) / len(logs[a]) - mu) ** 2 for a in rl.AGES if logs[a])
    w(f"- share of the variance of log-cost (finite nodes) between Ages: **{100 * between / total_ss:.1f} %**; "
      f"within an Age (node content): **{100 * (1 - between / total_ss):.1f} %**")
    cheapest_a9 = min((n for n in finite if n["age"] == "A9"), key=lambda n: n["cost"])
    w(f"- cheapest A9 node: `{cheapest_a9['id']}` at **{rl.fmt_int(cheapest_a9['cost'])} RP**")
    w(f"- EffectiveCost = max({floor} × BaseCost, BaseCost × Π modifiers); no modifier source exists yet, so "
      "EffectiveCost = BaseCost today")
    w("")
    w("### Finite cost distribution by Age (RP; repeatables excluded)")
    w("")
    w("| Age | nodes | total | median | mean | min | max |")
    w("|---|---|---|---|---|---|---|")
    grand = 0
    for a in rl.AGES:
        s = rl.stats([n["cost"] for n in finite if n["age"] == a])
        grand += s["total"]
        w(f"| {a} | {s['n']} | {rl.fmt_int(s['total'])} | {rl.fmt_int(s['median'])} | {rl.fmt_int(s['mean'])} | "
          f"{rl.fmt_int(s['min'])} | {rl.fmt_int(s['max'])} |")
    w(f"| **all** | **{len(finite)}** | **{rl.fmt_int(grand)}** | | | | |")
    w("")
    w("### Tiers")
    w("")
    tiers = Counter(n["costRationale"]["tier"] for n in nodes)
    w(" · ".join(f"{t}: {tiers[t]}" for t in sorted(tiers)))
    w("")

    # ---------------------------------------------------------------- Eurekas
    eus = [(n, i, e) for n in nodes for i, e in enumerate(n.get("eurekas") or [])]
    w("## 3. Eurekas — curated")
    w("")
    w(f"- Eurekas: **{len(eus)}** on **{sum(1 for n in nodes if n.get('eurekas'))}** nodes; evaluable today "
      f"(`when` present): **{sum(1 for _, _, e in eus if e.get('when'))}**")
    src = Counter(e["source"] for _, _, e in eus)
    w("- source: " + " · ".join(f"{k} {src[k]}" for k in sorted(src)))
    kinds = Counter(e["kind"] for _, _, e in eus)
    w("- kind: " + " · ".join(f"{k} {kinds[k]}" for k in sorted(kinds)))
    classes = Counter(e["class"] for _, _, e in eus)
    w("- class: " + " · ".join(f"`{k}` {classes[k]}" for k in sorted(classes)))
    explicit = sum(1 for n in nodes if n.get("eurekas") and any(e.get("weight") is not None for e in n["eurekas"]))
    w(f"- nodes with explicit weights: **{explicit}**; with the default (ceiling ÷ N): "
      f"**{sum(1 for n in nodes if n.get('eurekas')) - explicit}**; largest per-node weight sum: "
      f"**{max(sum(eureka_weights(n, ceiling)) for n in nodes if n.get('eurekas')):.2f}** (ceiling {ceiling})")
    w(f"- credit: each fired condition pays weight × BaseCost ONCE, from one pool per node shared with foreign")
    w(f"  exposure (≤ {ceiling} × BaseCost and ≤ the remaining EffectiveCost; no overflow; provenance per source)")
    w("")
    # Independent implied / dead checks.
    stage_must = rl.must_direct(rl.parse(content["researchStage"]["requires"]))
    for a in list(stage_must):
        stage_must |= g.must[a]
    implied, dead = [], []
    for n, i, e in eus:
        if not e.get("when"):
            continue
        cond = rl.parse(e["when"])
        must = set(g.must[n["id"]]) | (stage_must if n.get("branch") else set())
        knowledge_only = not any(c for c in _cmps(cond))
        if knowledge_only and rl.holds(cond, must):
            implied.append(f"`{n['id']}` #{i}")
        cond_must = set(rl.must_direct(cond))
        for a in list(cond_must):
            cond_must |= g.must.get(a, set())
        if n["id"] in cond_must:
            dead.append(f"`{n['id']}` #{i}")
    w(f"- implied Eurekas (a knowledge condition true on every path to its node): **{len(implied)}**"
      + (" — " + ", ".join(implied) if implied else ""))
    w(f"- dead Eurekas (a condition that needs its own node): **{len(dead)}**"
      + (" — " + ", ".join(dead) if dead else ""))
    w("")
    w("| node | Age | # | kind | class | when | weight | max credit (RP) |")
    w("|---|---|---|---|---|---|---|---|")
    for n in nodes:
        ws = eureka_weights(n, ceiling)
        for i, e in enumerate(n.get("eurekas") or []):
            when = f"`{e['when']}`" if e.get("when") else "—"
            w(f"| `{n['id']}` | {n['age']} | {i} | {e['kind']} | {e['class']} | {when} | {ws[i]:.4g} | "
              f"{rl.fmt_int(ws[i] * n['cost'])} |")
    w("")

    # ---------------------------------------------------------------- Group B
    w("## 4. Group B — writing, law, numeration and record-keeping pathways")
    w("")
    full = g.reachable()
    stage = rl.parse(content["researchStage"]["requires"])
    w("Reachable = can ever complete when the excluded nodes never do (a fixpoint over the prerequisites).")
    w("")
    w("| excluded | reachable nodes | research stage reachable |")
    w("|---|---|---|")
    w(f"| nothing | {len(full)} of {len(nodes)} | {'yes' if rl.holds(stage, full) else 'no'} |")
    variants = [[s] for s in SCRIPTS] + [[s for s in SCRIPTS if s != keep] for keep in SCRIPTS] + [SCRIPTS]
    for ex in variants:
        r = g.reachable(ex)
        w(f"| {', '.join('`' + x + '`' for x in ex)} | {len(r)} | {'yes' if rl.holds(stage, r) else 'no'} |")
    w("")
    no_cun = g.reachable(["cuneiform"])
    w("Generic record-keeping nodes reachable without cuneiform: "
      + ", ".join(f"`{x}` {'yes' if x in no_cun else 'NO'}" for x in GROUP_B_GENERIC))
    w("")
    w("Babylonian-specific nodes (kept specific) reachable without cuneiform: "
      + ", ".join(f"`{x}` {'YES' if x in no_cun else 'no'}" for x in GROUP_B_SPECIFIC))
    w("")
    lost = [n["id"] for n in nodes if n["id"] not in no_cun and n["id"] != "cuneiform"]
    w(f"Nodes that need cuneiform on every path ({len(lost)}): " + ", ".join(f"`{x}`" for x in lost))
    w("")

    # ---------------------------------------------------------------- repeatables
    w("## 5. Repeatables — recursive research (mechanics DEFERRED)")
    w("")
    w("Each is available only when its own prerequisites hold AND every finite node of its own subtree is")
    w("complete (the per-subtree rule, encoded as data in `repeatable.availability`). Repeat levels are NOT")
    w("implemented: the engine completes a repeatable once (D-044 R11), and the level mechanics are deferred")
    w("(D-044 Part D T6; gate ruling 4).")
    w("")
    w("| node | subtree | finite nodes to exhaust (data) | counted | first-level cost | prerequisite |")
    w("|---|---|---|---|---|---|")
    for rid in content["researchSets"]["recursive"]:
        n = g.by_id[rid]
        av = n["repeatable"]["availability"]
        counted = sum(1 for f in finite if f.get("branch") == n.get("branch"))
        w(f"| `{rid}` | {av['subtree']} | {av['finite_nodes_to_exhaust']} | {counted} | {rl.fmt_int(n['cost'])} | "
          f"`{n.get('prereq')}` |")
    w("")

    # ---------------------------------------------------------------- baseline
    w("## 6. Baseline capabilities (outside the graph — available with zero completed nodes)")
    w("")
    w("| id | name | provided by | simulated |")
    w("|---|---|---|---|")
    for b in content["baseline"]:
        w(f"| `{b['id']}` | {b['name']} | {b['providedBy']} | {'yes' if b['simulated'] else 'no'} |")
    w("")
    w("Their ownership against the research corpus is classified in `docs/design/research-capability-ownership.md`.")
    w("")

    # ---------------------------------------------------------------- techniques
    rows = technique_candidates()
    w("## 7. Technique candidates (carried forward from the D-045 audit — flagged, NOT moved)")
    w("")
    if rows:
        w("| node | Age (D-045) | Age now | cost now | reason (D-045) |")
        w("|---|---|---|---|---|")
        for nid, age, reason in rows:
            n = g.by_id.get(nid)
            now = (n["age"], rl.fmt_int(n["cost"])) if n else ("removed", "—")
            w(f"| `{nid}` | {age} | {now[0]} | {now[1]} | {reason} |")
        w("")
    w(f"{len(rows)} candidates; the decision whether any becomes a technique rather than a node is open.")
    w("")
    return "\n".join(out)


def _cmps(node):
    kind = node[0]
    if kind == "cmp":
        yield node
    elif kind == "not":
        yield from _cmps(node[1])
    elif kind in ("and", "or"):
        for c in node[1]:
            yield from _cmps(c)


def main():
    rl.write_or_check(AUDIT, build(), sys.argv, TOOL)


if __name__ == "__main__":
    main()
